
async function createAll(sequelize, Room){
    try {
        const roomsData = [
            {
                "room_id": "20001",
                "hotel_id": "11001",
                "price": 100,
                "capacity": 150,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20002",
                "hotel_id": "11001",
                "price": 200,
                "capacity": 200,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20003",
                "hotel_id": "11001",
                "price": 300,
                "capacity": 100,
                "amenities": "TV, WiFi",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20004",
                "hotel_id": "11001",
                "price": 400,
                "capacity": 250,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 3,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20005",
                "hotel_id": "11001",
                "price": 500,
                "capacity": 180,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20006",
                "hotel_id": "11002",
                "price": 100,
                "capacity": 220,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20007",
                "hotel_id": "11002",
                "price": 200,
                "capacity": 180,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20008",
                "hotel_id": "11002",
                "price": 300,
                "capacity": 120,
                "amenities": "TV, WiFi",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": true
            },
            {
                "room_id": "20009",
                "hotel_id": "11002",
                "price": 400,
                "capacity": 300,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 3,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20010",
                "hotel_id": "11002",
                "price": 500,
                "capacity": 250,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20011",
                "hotel_id": "11003",
                "price": 100,
                "capacity": 180,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20012",
                "hotel_id": "11003",
                "price": 200,
                "capacity": 150,
                "amenities": "TV, WiFi",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20013",
                "hotel_id": "11003",
                "price": 300,
                "capacity": 220,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20014",
                "hotel_id": "11003",
                "price": 400,
                "capacity": 300,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 3,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20015",
                "hotel_id": "11003",
                "price": 500,
                "capacity": 250,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20016",
                "hotel_id": "11004",
                "price": 100,
                "capacity": 80,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20017",
                "hotel_id": "11004",
                "price": 200,
                "capacity": 75,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20018",
                "hotel_id": "11004",
                "price": 300,
                "capacity": 80,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20019",
                "hotel_id": "11004",
                "price": 400,
                "capacity": 75,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20020",
                "hotel_id": "11004",
                "price": 500,
                "capacity": 80,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20021",
                "hotel_id": "11005",
                "price": 100,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20022",
                "hotel_id": "11005",
                "price": 200,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20023",
                "hotel_id": "11005",
                "price": 300,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20024",
                "hotel_id": "11005",
                "price": 400,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20025",
                "hotel_id": "11005",
                "price": 500,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            }
            ,{
                "room_id": "20026",
                "hotel_id": "11006",
                "price": 100,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20027",
                "hotel_id": "11006",
                "price": 200,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20028",
                "hotel_id": "11006",
                "price": 300,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20029",
                "hotel_id": "11006",
                "price": 400,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20030",
                "hotel_id": "11006",
                "price": 500,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20031",
                "hotel_id": "11007",
                "price": 100,
                "capacity": 120,
                "amenities": "Air conditioning, TV, minibar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20032",
                "hotel_id": "11007",
                "price": 200,
                "capacity": 140,
                "amenities": "Air conditioning, TV, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20033",
                "hotel_id": "11007",
                "price": 300,
                "capacity": 90,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20034",
                "hotel_id": "11007",
                "price": 400,
                "capacity": 200,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20035",
                "hotel_id": "11007",
                "price": 500,
                "capacity": 70,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20036",
                "hotel_id": "11008",
                "price": 100,
                "capacity": 130,
                "amenities": "Air conditioning, TV, minibar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20037",
                "hotel_id": "11008",
                "price": 200,
                "capacity": 160,
                "amenities": "Air conditioning, TV, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20038",
                "hotel_id": "11008",
                "price": 300,
                "capacity": 110,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20039",
                "hotel_id": "11008",
                "price": 400,
                "capacity": 250,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20040",
                "hotel_id": "11008",
                "price": 500,
                "capacity": 90,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20101",
                "hotel_id": "12001",
                "price": 100,
                "capacity": 150,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20102",
                "hotel_id": "12001",
                "price": 200,
                "capacity": 200,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20103",
                "hotel_id": "12001",
                "price": 300,
                "capacity": 100,
                "amenities": "TV, WiFi",


                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20104",
                "hotel_id": "12001",
                "price": 400,
                "capacity": 250,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 3,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20105",
                "hotel_id": "12001",
                "price": 500,
                "capacity": 180,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            }
            ,{
                "room_id": "20106",
                "hotel_id": "12002",
                "price": 100,
                "capacity": 220,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20107",
                "hotel_id": "12002",
                "price": 200,
                "capacity": 180,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20108",
                "hotel_id": "12002",
                "price": 300,
                "capacity": 120,
                "amenities": "TV, WiFi",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20109",
                "hotel_id": "12002",
                "price": 400,
                "capacity": 300,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 3,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20110",
                "hotel_id": "12002",
                "price": 500,
                "capacity": 250,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20111",
                "hotel_id": "12003",
                "price": 100,
                "capacity": 180,
                "amenities": "TV, WiFi, minibar",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20112",
                "hotel_id": "12003",
                "price": 200,
                "capacity": 150,
                "amenities": "TV, WiFi",
                "numberOfBeds": 1,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20113",
                "hotel_id": "12003",
                "price": 300,
                "capacity": 220,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20114",
                "hotel_id": "12003",
                "price": 400,
                "capacity": 300,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 3,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20115",
                "hotel_id": "12003",
                "price": 500,
                "capacity": 250,
                "amenities": "TV, WiFi, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20116",
                "hotel_id": "12004",
                "price": 100,
                "capacity": 80,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20117",
                "hotel_id": "12004",
                "price": 200,
                "capacity": 75,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20118",
                "hotel_id": "12004",
                "price": 300,
                "capacity": 80,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20119",
                "hotel_id": "12004",
                "price": 400,
                "capacity": 75,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20120",
                "hotel_id": "12004",
                "price": 500,
                "capacity": 80,
                "amenities": "Wifi, TV, Air conditioning, Mini bar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20121",
                "hotel_id": "12005",
                "price": 100,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20122",
                "hotel_id": "12005",
                "price": 200,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20123",
                "hotel_id":

                    "12005",
                "price": 300,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20124",
                "hotel_id": "12005",
                "price": 400,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20125",
                "hotel_id": "12005",
                "price": 500,
                "capacity": 100,
                "amenities": "Wifi, TV, Air conditioning, Balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20126",
                "hotel_id": "12006",
                "price": 100,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20127",
                "hotel_id": "12006",
                "price": 200,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20128",
                "hotel_id": "12006",
                "price": 300,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20129",
                "hotel_id": "12006",
                "price": 400,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": true
            },
            {
                "room_id": "20130",
                "hotel_id": "12006",
                "price": 500,
                "capacity": 60,
                "amenities": "Wifi, TV, Air conditioning",
                "numberOfBeds": 2,
                "hasTV": false,
                "hasWiFi": true,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20131",
                "hotel_id": "12007",
                "price": 100,
                "capacity": 120,
                "amenities": "Air conditioning, TV, minibar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20132",
                "hotel_id": "12007",
                "price": 200,
                "capacity": 140,
                "amenities": "Air conditioning, TV, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20133",
                "hotel_id": "12007",
                "price": 300,
                "capacity": 90,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20134",
                "hotel_id": "12007",
                "price": 400,
                "capacity": 200,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20135",
                "hotel_id": "12007",
                "price": 500,
                "capacity": 70,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20136",
                "hotel_id": "12008",
                "price": 100,
                "capacity": 130,
                "amenities": "Air conditioning, TV, minibar",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20137",
                "hotel_id": "12008",
                "price": 200,
                "capacity": 160,
                "amenities": "Air conditioning, TV, minibar, balcony",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": true,
                "hasBalcony": false
            },
            {
                "room_id": "20138",
                "hotel_id": "12008",
                "price": 300,
                "capacity": 120,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20139",
                "hotel_id": "12008",
                "price": 400,
                "capacity": 250,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 2,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },
            {
                "room_id": "20140",
                "hotel_id": "12008",
                "price": 500,
                "capacity": 90,
                "amenities": "Air conditioning, TV",
                "numberOfBeds": 1,
                "hasTV": true,
                "hasWiFi": false,
                "hasMinibar": false,
                "hasBalcony": false
            },

            {"room_id": "20201", "hotel_id": "13001", "price": 100, "capacity": 150, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20202", "hotel_id": "13001", "price": 200, "capacity": 200, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20203", "hotel_id": "13001", "price": 300, "capacity": 100, "amenities": "TV, WiFi", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20204", "hotel_id": "13001", "price": 400, "capacity": 250, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 3, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20205", "hotel_id": "13001", "price": 500, "capacity": 180, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20206", "hotel_id": "13002", "price": 100, "capacity": 220, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20207", "hotel_id": "13002", "price": 200, "capacity": 180, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20208", "hotel_id": "13002", "price": 300, "capacity": 120, "amenities": "TV, WiFi", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20209", "hotel_id": "13002", "price": 400, "capacity": 300, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 3, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20210", "hotel_id": "13002", "price": 500, "capacity": 250, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20211", "hotel_id": "13003", "price": 100, "capacity": 180, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20212", "hotel_id": "13003", "price": 200, "capacity": 150, "amenities": "TV, WiFi", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20213", "hotel_id": "13003", "price": 300, "capacity": 220, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20214", "hotel_id": "13003", "price": 400, "capacity": 300, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 3, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20215", "hotel_id": "13003", "price": 500, "capacity": 250, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20216", "hotel_id": "13004", "price": 100, "capacity": 80, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20217", "hotel_id": "13004", "price": 200, "capacity": 75, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20218", "hotel_id": "13004", "price": 300, "capacity": 80, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20219", "hotel_id": "13004", "price": 400, "capacity": 75, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20220", "hotel_id": "13004", "price": 500, "capacity": 80, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20221", "hotel_id": "13005", "price": 100, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20222", "hotel_id": "13005", "price": 200, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20223", "hotel_id": "13005", "price": 300, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20224", "hotel_id": "13005", "price": 400, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20225", "hotel_id": "13005", "price": 500, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20226", "hotel_id": "13006", "price": 100, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20227", "hotel_id": "13006", "price": 200, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20228", "hotel_id": "13006", "price": 300, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20229", "hotel_id": "13006", "price": 400, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20230", "hotel_id": "13006", "price": 500, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20231", "hotel_id": "13007", "price": 100, "capacity": 120, "amenities": "Air conditioning, TV, minibar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20232", "hotel_id": "13007", "price": 200, "capacity": 140, "amenities": "Air conditioning, TV, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20233", "hotel_id": "13007", "price": 300, "capacity": 90, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": true, "hasWiFi": false, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20234", "hotel_id": "13007", "price": 400, "capacity": 200, "amenities": "Air conditioning, TV", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20235", "hotel_id": "13007", "price": 500, "capacity": 70, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": true, "hasWiFi": false, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20236", "hotel_id": "13008", "price": 100, "capacity": 130, "amenities": "Air conditioning, TV, minibar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20237", "hotel_id": "13008", "price": 200, "capacity": 160, "amenities": "Air conditioning, TV, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20238", "hotel_id": "13008", "price": 300, "capacity": 130, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": true, "hasWiFi": false, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20239", "hotel_id": "13008", "price": 400, "capacity": 250, "amenities": "Air conditioning, TV", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20240", "hotel_id": "13008", "price": 500, "capacity": 90, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": true, "hasWiFi": false, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20301", "hotel_id": "14001", "price": 100, "capacity": 150, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20302", "hotel_id": "14001", "price": 200, "capacity": 200, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20303", "hotel_id": "14001", "price": 300, "capacity": 100, "amenities": "TV, WiFi", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20304", "hotel_id": "14001", "price": 400, "capacity": 250, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 3, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20305", "hotel_id": "14001", "price": 500, "capacity": 180, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},

            {"room_id": "20306", "hotel_id": "14002", "price": 100, "capacity": 220, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20307", "hotel_id": "14002", "price": 200, "capacity": 180, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20308", "hotel_id": "14002", "price": 300, "capacity": 120, "amenities": "TV, WiFi", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20309", "hotel_id": "14002", "price": 400, "capacity": 300, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 3, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20310", "hotel_id": "14002", "price": 500, "capacity": 250, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20311", "hotel_id": "14003", "price": 100, "capacity": 180, "amenities": "TV, WiFi, minibar", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20312", "hotel_id": "14003", "price": 200, "capacity": 150, "amenities": "TV, WiFi", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20313", "hotel_id": "14003", "price": 300, "capacity": 220, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20314", "hotel_id": "14003", "price": 400, "capacity": 300, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 3, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20315", "hotel_id": "14003", "price": 500, "capacity": 250, "amenities": "TV, WiFi, minibar, balcony", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20316", "hotel_id": "14004", "price": 100, "capacity": 80, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20317", "hotel_id": "14004", "price": 200, "capacity": 75, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20318", "hotel_id": "14004", "price": 300, "capacity": 80, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20319", "hotel_id": "14004", "price": 400, "capacity": 75, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20320", "hotel_id": "14004", "price": 500, "capacity": 80, "amenities": "Wifi, TV, Air conditioning, Mini bar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20321", "hotel_id": "14005", "price": 100, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20322", "hotel_id": "14005", "price": 200, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20323", "hotel_id": "14005", "price": 300, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20324", "hotel_id": "14005", "price": 400, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20325", "hotel_id": "14005", "price": 500, "capacity": 100, "amenities": "Wifi, TV, Air conditioning, Balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20326", "hotel_id": "14006", "price": 100, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20327", "hotel_id": "14006", "price": 200, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20328", "hotel_id": "14006", "price": 300, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20329", "hotel_id": "14006", "price": 400, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20330", "hotel_id": "14006", "price": 500, "capacity": 60, "amenities": "Wifi, TV, Air conditioning", "numberOfBeds": 2, "hasTV": false, "hasWiFi": true, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20331", "hotel_id": "14007", "price": 100, "capacity": 120, "amenities": "Air conditioning, TV, minibar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20332", "hotel_id": "14007", "price": 200, "capacity": 140, "amenities": "Air conditioning, TV, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20333", "hotel_id": "14007", "price": 300, "capacity": 90, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20334", "hotel_id": "14007", "price": 400, "capacity": 200, "amenities": "Air conditioning, TV", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20335", "hotel_id": "14007", "price": 500, "capacity": 70, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": false, "hasWiFi": false, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20336", "hotel_id": "14008", "price": 100, "capacity": 130, "amenities": "Air conditioning, TV, minibar", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20337", "hotel_id": "14008", "price": 200, "capacity": 160, "amenities": "Air conditioning, TV, minibar, balcony", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": true},
            {"room_id": "20338", "hotel_id": "14008", "price": 300, "capacity": 150, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": false, "hasWiFi": true, "hasMinibar": false, "hasBalcony": false},
            {"room_id": "20339", "hotel_id": "14008", "price": 400, "capacity": 250, "amenities": "Air conditioning, TV", "numberOfBeds": 2, "hasTV": true, "hasWiFi": false, "hasMinibar": true, "hasBalcony": false},
            {"room_id": "20440", "hotel_id": "15008", "price": 500, "capacity": 90, "amenities": "Air conditioning, TV", "numberOfBeds": 1, "hasTV": false, "hasWiFi": false, "hasMinibar": false, "hasBalcony": false}

        ];

        // Use bulkCreate to insert multiple records at once
        //const rooms = await Room.bulkCreate(roomsData);

        const rooms = await Promise.all(roomsData.map(async(room) => {
            await Room.findOrCreate({
                where: {room_id: room.room_id},
                defaults: room,
                logging: false
            })
        }))

        console.log('Rooms inserted:');

    } catch (error) {
        console.error('Error inserting rooms:', error);
    }
}

module.exports = {createAll}